main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: beerops.dev
description: When Enderman lost in a tample at Hanoi, He must solve the accent Hanoi Towel mystery...
commands:
  dotower:
    description: Base command for Enderman Hanoi Tower
    usage: "For a list of commands, type /dotower help"
    aliases: enderman_hanoi_tower
permissions:
  eh.test:
    description: DESCRIPTION
    default: true
  eh.*:
    description: Grants all other permissions
    default: false
    children:
      eh.test: true